### ISSUE TITLE
Objects are not being printed.

### ISSUE THREAD

**Issue by ssmereka** [CMaylone/bunyan-pretty-stream#1]
Objects are not printed at all.

**Code**
```
var obj = {
  "myKey":  "myValue"
};
log.info(obj);
```
**Output**
```
[Fri, 05 Feb 2016 18:59:31 GMT] [INFO]:
```

However, %s does work as expected.

**Code**
```
var obj = {
  "myKey":  "myValue"
};
log.info('%s', obj);
```
**Output**
```
[Fri, 05 Feb 2016 19:00:23 GMT] [INFO]: [object Object]
```

**Comment by CMaylone** [comment]
I am deprecating this repo because I was basically starting to copy the exact same functionality of another project. I recommend using [node-bunyan-stream](https://github.com/mrrama/node-bunyan-prettystream) instead.
